/*
 * Copyright (c) 2018-2025, Alden Torres
 *
 * Licensed under the terms of the MIT license.
 * Copy of the license at https://opensource.org/licenses/MIT
 */

plugins {
    `java-library`
    `maven-publish`
    signing
    jacoco
}

group = "org.libtorrent4j"
// Fork versions: the libtorrent version, then a numeric build number from
// 1000 up (2.1.2-1000, 2.1.2-1001, ...), above any upstream libtorrent4j
// build number for the same libtorrent. Numeric only: Gradle orders a string
// part ("-fp.1") below the base version. What keeps an upstream build out of
// a consumer is its repository filter (exclusiveContent), not this number.
version = "2.1.2-1000"

java {
    // using java 8 for android compatibility
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8

    withJavadocJar()
    withSourcesJar()
}

val codacy: Configuration by configurations.creating

repositories {
    mavenCentral()
}

dependencies {

    testImplementation("junit:junit:4.13.2")

    //codacy("com.codacy:codacy-coverage-reporter:7.1.0")
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}

// The libtorrent the native library has to be built from: the version in the
// submodule's version.hpp and the submodule's git revision (or
// LT4J_LIBTORRENT_REVISION, if set). The native build bakes the same pair in
// (swig/Jamfile), and LibTorrent.nativeBuild() / expectedNativeBuild() let a
// client compare the two at startup instead of running with a native library
// from another build.
val libtorrentRoot = file("swig/deps/libtorrent")
val libtorrentRevision: Provider<String> = providers.environmentVariable("LT4J_LIBTORRENT_REVISION")
    .orElse(providers.exec {
        commandLine("git", "-C", libtorrentRoot.path, "rev-parse", "HEAD")
    }.standardOutput.asText.map { it.trim() })

val generateNativeBuildInfo by tasks.registering {
    val versionHpp = libtorrentRoot.resolve("include/libtorrent/version.hpp")
    val outDir = layout.buildDirectory.dir("generated/sources/nativeBuildInfo/java")
    val lt4jVersion = project.version.toString()
    inputs.file(versionHpp)
    inputs.property("revision", libtorrentRevision)
    inputs.property("version", lt4jVersion)
    outputs.dir(outDir)
    doLast {
        val ltVersion = Regex("#define LIBTORRENT_VERSION \"([^\"]+)\"")
            .find(versionHpp.readText())?.groupValues?.get(1)
            ?: throw GradleException("LIBTORRENT_VERSION not found in $versionHpp")
        val revision = libtorrentRevision.get()
        if (!Regex("[0-9a-f]{40}").matches(revision))
            throw GradleException("not a git revision of the libtorrent submodule: '$revision'")
        val file = outDir.get().file("org/libtorrent4j/NativeBuildInfo.java").asFile
        file.parentFile.mkdirs()
        file.writeText("""
            |package org.libtorrent4j;
            |
            |// generated by the generateNativeBuildInfo task in build.gradle.kts
            |final class NativeBuildInfo {
            |
            |    static final String LIBTORRENT_VERSION = "$ltVersion";
            |    static final String LIBTORRENT_REVISION = "$revision";
            |    static final String LIBTORRENT4J_VERSION = "$lt4jVersion";
            |
            |    private NativeBuildInfo() {
            |    }
            |}
            |""".trimMargin())
    }
}

sourceSets.main {
    java.srcDir(generateNativeBuildInfo)
}

tasks.test {
    testLogging {
        events("passed", "skipped", "failed", "standard_out")

        exceptionFormat = org.gradle.api.tasks.testing.logging.TestExceptionFormat.FULL
        showExceptions = true
        showCauses = true
        showStackTraces = true
    }

    systemProperty("file.encoding", "utf-8")
    systemProperty("java.library.path", file(".").absolutePath)
    environment("LD_LIBRARY_PATH", File(".").absolutePath)
}

tasks.register<Zip>("nativeMacOSJar") {
    destinationDirectory.set(layout.buildDirectory.dir("libs"))
    archiveBaseName.set("libtorrent4j-macos")
    archiveExtension.set("jar")

    from("swig/bin/release/macos") {
        include("**/*libtorrent4j.dylib")
        exclude("**/ed25519", "**/src", "**/*.dSYM")
        into("lib")
    }
}

tasks.register<Zip>("nativeWindowsJar") {
    destinationDirectory.set(layout.buildDirectory.dir("libs"))
    archiveBaseName.set("libtorrent4j-windows")
    archiveExtension.set("jar")

    from("swig/bin/release/windows") {
        include("**/*libtorrent4j.dll")
        exclude("**/ed25519", "**/src")
        into("lib")
    }
}

tasks.register<Zip>("nativeLinuxJar") {
    destinationDirectory.set(layout.buildDirectory.dir("libs"))
    archiveBaseName.set("libtorrent4j-linux")
    archiveExtension.set("jar")

    from("swig/bin/release/linux") {
        include("**/*libtorrent4j.so")
        exclude("**/ed25519", "**/src")
        into("lib")
    }
}

tasks.register<Zip>("nativeAndroidArmJar") {
    destinationDirectory.set(layout.buildDirectory.dir("libs"))
    archiveBaseName.set("libtorrent4j-android-arm")
    archiveExtension.set("jar")

    from("swig/bin/release/android") {
        include("armeabi-v7a/libtorrent4j.so")
        into("lib")
    }
}

tasks.register<Zip>("nativeAndroidX86Jar") {
    destinationDirectory.set(layout.buildDirectory.dir("libs"))
    archiveBaseName.set("libtorrent4j-android-x86")
    archiveExtension.set("jar")

    from("swig/bin/release/android") {
        include("x86/libtorrent4j.so")
        into("lib")
    }
}

tasks.register<Zip>("nativeAndroidArm64Jar") {
    destinationDirectory.set(layout.buildDirectory.dir("libs"))
    archiveBaseName.set("libtorrent4j-android-arm64")
    archiveExtension.set("jar")

    from("swig/bin/release/android") {
        include("arm64-v8a/libtorrent4j.so")
        into("lib")
    }
}

tasks.register<Zip>("nativeAndroidX64Jar") {
    destinationDirectory.set(layout.buildDirectory.dir("libs"))
    archiveBaseName.set("libtorrent4j-android-x86_64")
    archiveExtension.set("jar")

    from("swig/bin/release/android") {
        include("x86_64/libtorrent4j.so")
        into("lib")
    }
}

tasks.withType<GenerateModuleMetadata> {
    enabled = false
}

fun generatePom(pomName: String, addDeps: Boolean = false) = Action<org.gradle.api.publish.maven.MavenPom> {
    name.set(pomName)
    description.set("A swig Java interface for libtorrent")
    url.set("https://github.com/aldenml/libtorrent4j")
    scm {
        connection.set("scm:git:git://github.com/aldenml/libtorrent4j.git")
        developerConnection.set("scm:git:ssh:git@github.com/aldenml/libtorrent4j.git")
        url.set("https://github.com/aldenml/libtorrent4j")
    }
    licenses {
        license {
            name.set("The MIT License")
            url.set("https://github.com/aldenml/libtorrent4j/blob/master/LICENSE.md")
        }
    }
    developers {
        developer {
            id.set("aldenml")
            name.set("Alden Torres")
            email.set("aldenml@gmail.com")
        }
    }

    if (addDeps)
        withXml {
            val root = asNode()
            val dependenciesNode = root.appendNode("dependencies")
            val depNode = dependenciesNode.appendNode("dependency")
            depNode.appendNode("groupId", group)
            depNode.appendNode("artifactId", "libtorrent4j")
            depNode.appendNode("version", version)
        }
}

publishing {
    publications {
        create<MavenPublication>("mavenJava") {
            artifactId = "libtorrent4j"
            from(components["java"])
            pom(generatePom(artifactId))
        }
        create<MavenPublication>("mavenMacOS") {
            artifactId = "libtorrent4j-macos"
            artifact(tasks["nativeMacOSJar"])
            pom(generatePom(artifactId, true))
        }
        create<MavenPublication>("mavenWindows") {
            artifactId = "libtorrent4j-windows"
            artifact(tasks["nativeWindowsJar"])
            pom(generatePom(artifactId, true))
        }
        create<MavenPublication>("mavenLinux") {
            artifactId = "libtorrent4j-linux"
            artifact(tasks["nativeLinuxJar"])
            pom(generatePom(artifactId, true))
        }
        create<MavenPublication>("mavenAndroidArm") {
            artifactId = "libtorrent4j-android-arm"
            artifact(tasks["nativeAndroidArmJar"])
            pom(generatePom(artifactId, true))
        }
        create<MavenPublication>("mavenAndroidX86") {
            artifactId = "libtorrent4j-android-x86"
            artifact(tasks["nativeAndroidX86Jar"])
            pom(generatePom(artifactId, true))
        }
        create<MavenPublication>("mavenAndroidArm64") {
            artifactId = "libtorrent4j-android-arm64"
            artifact(tasks["nativeAndroidArm64Jar"])
            pom(generatePom(artifactId, true))
        }
        create<MavenPublication>("mavenAndroidX64") {
            artifactId = "libtorrent4j-android-x86_64"
            artifact(tasks["nativeAndroidX64Jar"])
            pom(generatePom(artifactId, true))
        }
    }

    repositories {
        maven {
            credentials {
                username = if (hasProperty("ossrhUsername"))
                    property("ossrhUsername").toString() else ""
                password = if (hasProperty("ossrhPassword"))
                    property("ossrhPassword").toString() else ""
            }
            url = uri("https://ossrh-staging-api.central.sonatype.com/service/local/staging/deploy/maven2/")
        }
    }
}

signing {
    sign(publishing.publications["mavenJava"])
    sign(publishing.publications["mavenMacOS"])
    sign(publishing.publications["mavenWindows"])
    sign(publishing.publications["mavenLinux"])
    sign(publishing.publications["mavenAndroidArm"])
    sign(publishing.publications["mavenAndroidX86"])
    sign(publishing.publications["mavenAndroidArm64"])
    sign(publishing.publications["mavenAndroidX64"])
}

tasks.jacocoTestReport {
    reports {
        xml.required = true
    }
}

//tasks.register<JavaExec>("codacyCoverage") {
//    dependsOn(tasks.jacocoTestReport)
//
//    main = "com.codacy.CodacyCoverageReporter"
//    classpath = codacy
//    args = listOf(
//        "report",
//        "-l",
//        "Java",
//        "-r",
//        "${layout.buildDirectory}/reports/jacoco/test/jacocoTestReport.xml"
//    )
//}
