#!/bin/bash
# Writes swig/lt4j_revision.hpp with the git revision of the libtorrent
# submodule (or $LT4J_LIBTORRENT_REVISION, if set) and the libtorrent4j version
# from build.gradle.kts, for ext_jni.cpp to report through
# libtorrent_ext.nativeBuild(). The file is only rewritten when its content
# changes, so b2 recompiles ext_jni.cpp exactly when either moved, including
# in incremental builds.
set -euo pipefail
here=$(cd "$(dirname "$0")" && pwd)
rev=${LT4J_LIBTORRENT_REVISION:-$(git -C "$here/deps/libtorrent" rev-parse HEAD)}
# a full revision, as the Gradle side (generateNativeBuildInfo) requires; a
# short one would build here and fail there
[[ $rev =~ ^[0-9a-f]{40}$ ]] || { echo "not a full git revision (40 hex digits): '$rev'" >&2; exit 2; }
version=$(sed -n 's/^version = "\(.*\)"$/\1/p' "$here/../build.gradle.kts")
[ -n "$version" ] || { echo "cannot read version from build.gradle.kts" >&2; exit 2; }
out=$here/lt4j_revision.hpp
new="// generated by swig/write-revision-header.sh, do not edit
#define LT4J_LIBTORRENT_REVISION \"$rev\"
#define LT4J_VERSION \"$version\""
if [ ! -f "$out" ] || [ "$(cat "$out")" != "$new" ]; then
    printf '%s\n' "$new" > "$out"
fi
