#!/bin/bash
# Writes swig/lt4j_revision.hpp with the git revision of the libtorrent
# submodule (or $LT4J_LIBTORRENT_REVISION, if set), for ext_jni.cpp to report
# through libtorrent_ext.nativeBuild(). The file is only rewritten when its
# content changes, so b2 recompiles ext_jni.cpp exactly when the revision
# moved, including in incremental builds.
set -euo pipefail
here=$(cd "$(dirname "$0")" && pwd)
rev=${LT4J_LIBTORRENT_REVISION:-$(git -C "$here/deps/libtorrent" rev-parse HEAD)}
case $rev in
    *[!0-9a-f]*|"") echo "not a git revision: '$rev'" >&2; exit 2 ;;
esac
out=$here/lt4j_revision.hpp
new="// generated by swig/write-revision-header.sh, do not edit
#define LT4J_LIBTORRENT_REVISION \"$rev\""
if [ ! -f "$out" ] || [ "$(cat "$out")" != "$new" ]; then
    printf '%s\n' "$new" > "$out"
fi
