/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libtorrent4j.swig;

public class ip_ban_alert extends alert {
  private transient long swigCPtr;

  protected ip_ban_alert(long cPtr, boolean cMemoryOwn) {
    super(libtorrent_jni.ip_ban_alert_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ip_ban_alert obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(ip_ban_alert obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libtorrent_jni.delete_ip_ban_alert(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public int type() {
    return libtorrent_jni.ip_ban_alert_type(swigCPtr, this);
  }

  public alert_category_t category() {
    return new alert_category_t(libtorrent_jni.ip_ban_alert_category(swigCPtr, this), true);
  }

  public String what() {
    return libtorrent_jni.ip_ban_alert_what(swigCPtr, this);
  }

  public String message() {
    return libtorrent_jni.ip_ban_alert_message(swigCPtr, this);
  }

  public void setBanned_address(SWIGTYPE_p_libtorrent__aux__noexcept_movableT_libtorrent__address_t value) {
    libtorrent_jni.ip_ban_alert_banned_address_set(swigCPtr, this, SWIGTYPE_p_libtorrent__aux__noexcept_movableT_libtorrent__address_t.getCPtr(value));
  }

  public SWIGTYPE_p_libtorrent__aux__noexcept_movableT_libtorrent__address_t getBanned_address() {
    long cPtr = libtorrent_jni.ip_ban_alert_banned_address_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__aux__noexcept_movableT_libtorrent__address_t(cPtr, false);
  }

  public final static alert_priority priority = alert_priority.swigToEnum(libtorrent_jni.ip_ban_alert_priority_get());
  public final static int alert_type = libtorrent_jni.ip_ban_alert_alert_type_get();
  public final static alert_category_t static_category = new alert_category_t(libtorrent_jni.ip_ban_alert_static_category_get(), false);
}
